# Generated by Django 3.2.7 on 2022-08-05 11:32

from django.db import migrations, models
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_recipeingredients_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[recipe.validators.validate_unit_measure]),
        ),
    ]
