# Generated by Django 3.2.7 on 2022-07-08 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
